import io
import tempfile
import unittest
from datetime import UTC, datetime
from unittest import mock

from nixkeeper_versions import stackage

NOW = datetime(2026, 10, 8, 4, 10, tzinfo=UTC)

# Trimmed from nixpkgs' stackage.yaml and stackage.org's cabal.config
# (2026-10-07).
PINS = b"""# Stackage LTS 24.38
# This file is auto-generated by
# maintainers/scripts/haskell/update-stackage.sh
default-package-overrides:
  - abstract-deque ==0.3
  - aeson ==2.2.3.0
  - zot ==0.0.3
"""
SNAPSHOT = b"""-- NOTE: Due to revisions, this file may not work. See:
-- Stackage snapshot from: http://www.stackage.org/snapshot/lts-24.62
-- remote-repo: stackage-lts-24.62:http://www.stackage.org/lts-24.62
with-compiler: ghc-9.10.3
constraints: abstract-deque ==0.3,
             aeson ==2.2.4.1,
             array installed,
             base installed,
             zot ==0.0.3,
             zstd ==0.1.4.0
"""
BODIES = {
    stackage.NIXPKGS_PINS: PINS,
    "https://www.stackage.org/lts-24/cabal.config": SNAPSHOT,
}


class Parse(unittest.TestCase):
    def test_which_series_nixpkgs_follows(self):
        self.assertEqual(stackage.followed(PINS.decode()), ("lts-24", "lts-24.38"))
        with self.assertRaises(ValueError):
            stackage.followed("default-package-overrides:\n")

    def test_pins(self):
        self.assertEqual(
            stackage.pins(PINS.decode()), {"abstract-deque", "aeson", "zot"}
        )

    def test_snapshot(self):
        found, versions = stackage.snapshot(SNAPSHOT.decode())
        self.assertEqual(found, "lts-24.62")
        # GHC's own ("installed") aren't versions.
        self.assertEqual(
            versions,
            {
                "abstract-deque": "0.3",
                "aeson": "2.2.4.1",
                "zot": "0.0.3",
                "zstd": "0.1.4.0",
            },
        )


class Update(unittest.TestCase):
    def setUp(self):
        for patcher in (
            mock.patch("sys.stderr", io.StringIO()),
            mock.patch.object(stackage, "MIN_PACKAGES", 1),
        ):
            patcher.start()
            self.addCleanup(patcher.stop)

    def serve(self, bodies):
        def get(url):
            if bodies.get(url) is None:
                raise OSError(f"{url}: down")
            return bodies[url]

        return mock.patch.object(stackage.download, "get", side_effect=get)

    def test_written_and_read(self):
        with tempfile.TemporaryDirectory() as d, self.serve(BODIES):
            self.assertEqual(
                stackage.update(d, NOW),
                {
                    "at": "2026-10-08T04:10:00+00:00",
                    "snapshot": "lts-24.62",
                    "packages": 3,
                },
            )
            found = stackage.read(d)
        self.assertEqual(
            (found["series"], found["nixpkgs"], found["snapshot"]),
            ("lts-24", "lts-24.38", "lts-24.62"),
        )
        # Only what nixpkgs pins (not zstd), at the snapshot's version.
        self.assertEqual(
            found["versions"],
            {"abstract-deque": "0.3", "aeson": "2.2.4.1", "zot": "0.0.3"},
        )

    def test_the_last_stays(self):
        with tempfile.TemporaryDirectory() as d:
            with self.serve(BODIES):
                stackage.update(d, NOW)
            before = stackage.read(d)
            with self.serve({**BODIES, stackage.NIXPKGS_PINS: None}):
                self.assertIsNone(stackage.update(d, NOW))
            with self.serve(BODIES), mock.patch.object(stackage, "MIN_PACKAGES", 5):
                self.assertIsNone(stackage.update(d, NOW))
            self.assertEqual(stackage.read(d), before)


if __name__ == "__main__":
    unittest.main()
